<a href="https://colab.research.google.com/github/veorte/registros/blob/main/Actividad3BDManipulacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MAESTRÍA EN INTELIGENCIA ARTIFICIAL APLICADA**

**Curso: TC5053 - Ciencia y analítica de datos**

Tecnológico de Monterrey

Prof Grettel Barceló Alonso

**Semana 3**
Bases, almacenes y manipulación de datos

---

*   NOMBRE: VERONICA ORTEGA LOPEZ
*   MATRÍCULA: A01841596

---

En esta actividad usarás una base de datos relacional basada en el informe de participación y la lista del top 10 de Netflix. Incluye películas y programas de televisión, así como información sobre temporadas, métricas de visualización, fechas de estreno, duración y más, organizada en las siguientes tablas:

* `movie`: Información general de las películas.

* `tv_show`: Información general de los programas de televisión.

* `season`: Datos de las temporadas asociadas a cada programa de TV.

* `view_summary`: Métricas de visualización y rendimiento de películas o temporadas.

Revisa con detalle su esquema para que comprendas cómo se relacionan las tablas anteriores.

**NOTA IMPORTANTE:** Asegúrate de responder *explícitamente* todos los cuestionamientos.

`PyMySQL` es una librería escrita en Python puro que funciona como conector (*driver*) para motores de bases de datos MySQL, permitiendo abrir conexiones, ejecutar consultas SQL y recuperar resultados directamente desde programas en Python.

In [4]:
pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.7/46.7 kB 4.0 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3

`SQLAlchemy` es una librería de Python que facilita la interacción con bases de datos y permite mantener un pool de conexiones eficiente, gestionar *commits* y *rollbacks* de forma automática y asegurar que múltiples conexiones simultáneas se manejen de manera segura, incluso cuando se ejecutan consultas SQL “puras”

In [2]:
# Importa las librerías necesarias
import pymysql
import sqlalchemy as sqla
import pandas as pd

Se crea una conexión (`conn`) para luego invocar declaraciones SQL.

In [3]:
# motor+driver://usuarioBD:clave@ipHostDBMS:puerto/esquema
# pool_recycle controla el tiempo máximo de vida de una conexión en el pool (3600 segundos = 1 hora)
db = sqla.create_engine(
    'mysql+pymysql://mnaTC5053User:mnaTC5053Pass!@20.127.169.219:3306/Netflix',
    pool_recycle=3600,
    pool_pre_ping=True,
    pool_size=1,
    max_overflow=0)
conn = db.connect()

Para que tus consultas sean más legibles y fáciles de mantener, puedes usar este formato multilínea con comillas triples y `sqla.text()`. Por ejemplo:

```
query = sqla.text("""
  SELECT ---
  FROM ---
  WHERE ---
""")
pd.read_sql(query, conn)
```

1.	Extrae toda la información de las películas que duran más de 5 horas.

In [4]:
query = sqla.text("""
    SELECT *
    FROM movie
    WHERE runtime > 300
""")

movies_5h = pd.read_sql(query, conn)

movies_5h

,id,created_date,modified_date,available_globally,locale,original_title,release_date,runtime,title
0,5793,2024-01-01,2024-01-01,b'\x00',None,日本統一シリーズ: 映画シリーズ,None,3892,Nihontouitsu Series: Film Series
1,5794,2024-01-01,2024-01-01,b'\x00',None,釣りバカ日誌: 映画シリーズ,None,2120,Free and Easy Series: Film Series
2,5874,2024-01-01,2024-01-01,b'\x01',None,None,2021-08-06,312,Navarasa: Limited Series
3,9729,2024-01-01,2024-01-01,b'\x00',None,織田同志会 織田征仁: 映画シリーズ,None,710,Seiji Oda: Film Series
4,9730,2024-01-01,2024-01-01,b'\x00',None,キングダム～首領になった男～: 映画シリーズ,None,427,Kingdom ~ The Man Who Became the Top ~: Film S...

Hay 4 peliculas que duran mas de 5 horas (300 minutos)

2.	¿Cuál es el porcentaje de películas disponibles únicamente en EU en relación con el total, excluyendo los valores `NULL`? La consulta SQL debe entregar directamente el porcentaje final. No se deben devolver resultados parciales para realizar el cálculo en Python.

In [5]:
query = sqla.text("""
    SELECT DISTINCT available_globally
    FROM movie
""")

pd.read_sql(query, conn)

  available_globally
0            b'\x01'
1            b'\x00'
2               None

In [6]:
query = sqla.text("""
    SELECT
        100.0 * SUM(available_globally = 0) /
        COUNT(available_globally) AS percentage_only_us
    FROM movie
    WHERE available_globally IS NOT NULL
""")

pd.read_sql(query, conn)

   percentage_only_us
0            83.57175

Hay un 83.57175% de peliculas disponibles únicamente en EU en relación con el total.

3.	¿Cuáles son los idiomas o regiones originales en la tabla de películas?
* ¿Cuántos registros tienen el campo `locale` con valor `NULL`? (NULL en SQL ⇔ None en Python)

In [7]:
query = sqla.text("""
    SELECT DISTINCT locale
    FROM movie
    ORDER BY locale
""")

pd.read_sql(query, conn)

  locale
0   None
1     en

Unicamente aparece idioma EN

In [7]:
query = sqla.text("""
    SELECT COUNT(*) AS null_locale_count
    FROM movie
    WHERE locale IS NULL
""")

pd.read_sql(query, conn)

   null_locale_count
0              11255

11,255 registros tienen el campo locale con valor NULL

4.	Asumiendo que los valores `NULL` en `locale` corresponden a otro idioma (diferente del inglés), el título original de la película NO debería coincidir con el título principal en dichos registros.
* Determina cuántas películas tienen títulos diferentes en estos dos campos (`title` y `original_title`).
*  ¿Coinciden los resultados (cantidad de `NULL` y títulos diferentes)? Si no es así, identifica qué características tienen los registros restantes.
* Finalmente, concluye si la suposición de que los valores `NULL` en `locale` indican que la película está en otro idioma es válida.

In [8]:
query = sqla.text("""
    SELECT COUNT(*) AS different_titles
    FROM movie
    WHERE title <> original_title
""")

pd.read_sql(query, conn)

   different_titles
0              3947

3,947 peliculas tienen diferencias entre los campos title y original title

In [9]:
query = sqla.text("""
    SELECT
        title,
        original_title,
        locale
    FROM movie
    WHERE locale IS NULL
""")

pd.read_sql(query, conn)

                                        title           original_title locale
0                                      Damsel                     None   None
1                                        Lift                     None   None
2                         Society of the Snow  La sociedad de la nieve   None
3                                 Under Paris            Sous la Seine   None
4                 The Super Mario Bros. Movie                     None   None
...                                       ...                      ...    ...
11250                        Faithfully Yours                     None   None
11251                          King of Clones                     None   None
11252  Black Clover: Sword of the Wizard King                     None   None
11253                              You Do You                     None   None
11254                            Mother's Day                     None   None

[11255 rows x 3 columns]

In [10]:
query = sqla.text("""
    SELECT
        title,
        original_title,
        locale
    FROM movie
    WHERE locale IS NULL
      AND title = original_title
""")

pd.read_sql(query, conn)

                             title                  original_title locale
0                   Recep Ivedik 7                  Recep İvedik 7   None
1                         Veronica                        Verónica   None
2                         Fantomas                        Fantômas   None
3   Luccas Neto em: O Hotel Magico  Luccas Neto em: O Hotel Mágico   None
4             Un Dia En El Paraiso            Un día en el paraíso   None
5                       Superlopez                      Superlópez   None
6             Baris Akarsu Merhaba            Barış Akarsu Merhaba   None
7                            Totem                           Tótem   None
8                   La Pena Maxima                  La pena máxima   None
9                       Mirciulica                      Mirciulică   None
10                          Animas                          Ánimas   None
11                    Dejame Vivir                    Déjame Vivir   None
12            Gangster Ka: African            Gangster Ka: Afričan   None
13                      Party Hard                      Párty Hárd   None
14                         Extasis                         Éxtasis   None
15                       Malefique                       Maléfique   None
16                        Tiramisu                        Tiramisù   None

In [11]:
query = sqla.text("""
    SELECT
        SUM(title IS NULL) AS null_title,
        SUM(original_title IS NULL) AS null_original_title
    FROM movie
""")

pd.read_sql(query, conn)

   null_title  null_original_title
0         0.0               7823.0

¿Coinciden los resultados (cantidad de NULL y títulos diferentes)? Si no es así, identifica qué características tienen los registros restantes.
***No, no coinciden.   El idioma de la pelicula es diferente.***

Finalmente, concluye si la suposición de que los valores NULL en locale indican que la película está en otro idioma es válida.
***La suposición es válida***

5.	Determina el título de la película que ha permanecido más tiempo en el top 10.

In [8]:
query = sqla.text("""
    SELECT
        m.title,
        v.cumulative_weeks_in_top10
    FROM movie AS m
    INNER JOIN view_summary AS v
        ON m.id = v.movie_id
    WHERE v.duration = 'WEEKLY'
    ORDER BY v.cumulative_weeks_in_top10 DESC
    LIMIT 1
""")

pd.read_sql(query, conn)

           title  cumulative_weeks_in_top10
0  The Boss Baby                         22

La pelicula que ha permanecido más tiempo en el top 10 es "The boss baby"

6.	Identifica los 5 programas de TV con mayor cantidad de temporadas.

In [9]:
query = sqla.text("""
    SELECT
        t.title,
        COUNT(s.id) AS number_of_seasons
    FROM tv_show AS t
    INNER JOIN season AS s
        ON t.id = s.tv_show_id
    GROUP BY
        t.id,
        t.title
    ORDER BY
        number_of_seasons DESC
    LIMIT 5
""")

pd.read_sql(query, conn)

                               title  number_of_seasons
0                     Grey's Anatomy                 20
1                   Naruto Shippuden                 20
2                   Heartland (2007)                 17
3  It's Always Sunny in Philadelphia                 16
4                               NCIS                 15

7.	¿Cuáles son los intervalos de fechas de los resúmenes en la tabla `view_summary` de los períodos (`duration`) semestrales?

In [10]:
query = sqla.text("""
    SELECT DISTINCT
        start_date,
        end_date
    FROM view_summary
    WHERE duration = 'SEMI_ANNUALLY'
    ORDER BY start_date
""")

pd.read_sql(query, conn)

   start_date    end_date
0  2023-07-01  2023-12-31
1  2024-01-01  2024-06-30

8.	Ordena las temporadas de *Grey's Anatomy* según la cantidad de vistas registradas en el primer período semestral de 2024.
* ¿Cómo interpretarías los resultados obtenidos?

In [11]:
query = sqla.text("""
    SELECT *
    FROM tv_show
    WHERE title = 'Grey''s Anatomy'
""")

pd.read_sql(query, conn)

,id,created_date,modified_date,available_globally,locale,original_title,release_date,title
0,347,2024-01-01,2024-01-01,b'\x00',None,None,None,Grey's Anatomy

In [12]:
query = sqla.text("""
    SELECT
        t.title AS tv_show,
        s.season_number,
        s.title AS season_title,
        v.views
    FROM tv_show AS t
    INNER JOIN season AS s
        ON t.id = s.tv_show_id
    INNER JOIN view_summary AS v
        ON s.id = v.season_id
    WHERE t.title = 'Grey''s Anatomy'
      AND v.duration = 'SEMI_ANNUALLY'
      AND v.start_date = '2024-01-01'
    ORDER BY v.views DESC
""")

greys_sql = pd.read_sql(query, conn)

greys_sql

           tv_show  season_number               season_title    views
0   Grey's Anatomy              1   Grey's Anatomy: Season 1  3600000
1   Grey's Anatomy              2   Grey's Anatomy: Season 2  3100000
2   Grey's Anatomy              3   Grey's Anatomy: Season 3  2900000
3   Grey's Anatomy              5   Grey's Anatomy: Season 5  2900000
4   Grey's Anatomy              4   Grey's Anatomy: Season 4  2900000
5   Grey's Anatomy              6   Grey's Anatomy: Season 6  2800000
6   Grey's Anatomy              7   Grey's Anatomy: Season 7  2700000
7   Grey's Anatomy              8   Grey's Anatomy: Season 8  2600000
8   Grey's Anatomy              9   Grey's Anatomy: Season 9  2500000
9   Grey's Anatomy             10  Grey's Anatomy: Season 10  2400000
10  Grey's Anatomy             11  Grey's Anatomy: Season 11  2200000
11  Grey's Anatomy             12  Grey's Anatomy: Season 12  2000000
12  Grey's Anatomy             13  Grey's Anatomy: Season 13  2000000
13  Grey's Anatomy             14  Grey's Anatomy: Season 14  2000000
14  Grey's Anatomy             19  Grey's Anatomy: Season 19  2000000
15  Grey's Anatomy             15  Grey's Anatomy: Season 15  1900000
16  Grey's Anatomy             16  Grey's Anatomy: Season 16  1800000
17  Grey's Anatomy             18  Grey's Anatomy: Season 18  1700000
18  Grey's Anatomy             17  Grey's Anatomy: Season 17  1700000
19  Grey's Anatomy             20  Grey's Anatomy: Season 20   100000

La temporada con mayores vistas durante el primer periodo semestral de 2024 fue la temporada 1.
Las vistas van disminuyendo para las temporadas subsecuentes, siendo la temporada 20 la que menos vistas registras.

9.	Todas las consultas anteriores podrían hacerse también con la lógica relacional implementada en Pandas, que permite replicar la mayoría de las operaciones de SQL. Si los dataframes se han llenado como sigue, resuelve la consulta 8 utilizando las funciones de Pandas.

In [13]:
tv_show = pd.read_sql(sqla.text('SELECT * FROM tv_show'), conn)
season = pd.read_sql(sqla.text('SELECT * FROM season'), conn)
view_summary = pd.read_sql(sqla.text('SELECT * FROM view_summary'), conn)

In [14]:
greys = tv_show[
    tv_show['title'] == "Grey's Anatomy"
]

In [16]:
# Estoy uniendo la serie con sus temporadas
greys_seasons = greys.merge(
    season,
    left_on='id',
    right_on='tv_show_id',
    suffixes=('_show', '_season')
)

In [17]:
# Agregamos las metricas
greys_views = greys_seasons.merge(
    view_summary,
    left_on='id_season',
    right_on='season_id'
)

In [18]:
# Filtremos el primer semestre de 2024
greys_2024_h1 = greys_views[
    (greys_views['duration'] == 'SEMI_ANNUALLY') &
    (greys_views['start_date'] == '2024-01-01')
]

In [20]:
# Ordenamos por vistas
greys_2024_h1 = greys_2024_h1.sort_values(
    by='views',
    ascending=False
)

In [21]:
greys_2024_h1[
    ['season_number', 'title_season', 'views']
]

Empty DataFrame
Columns: [season_number, title_season, views]
Index: []

`MySQL` es un sistema de gestión de bases de datos relacional, pero desde Python también es posible extraer información de bases de datos no relacionales, como `Firestore`, `MongoDB` o `Cassandra`, utilizando conectores o integraciones específicas. Esto permite combinar datos de diferentes fuentes según las necesidades del análisis o la aplicación.

En el siguiente ejercicio usarás un ejemplo con `Firestore` desde Python. Para ello utilizarás los módulos `credentials` y `firestore` de la biblioteca `firebase_admin`.

In [22]:
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

En `Firestore`, a diferencia de `MySQL` donde se utiliza un usuario y contraseña para conectarse, la autenticación se realiza mediante un archivo JSON que almacena las credenciales necesarias para acceder a la base de datos. Este archivo contiene las claves y la información de configuración que permiten a Python establecer la conexión de manera segura.

In [23]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [26]:
# Debes descargar el archivo de credenciales "consultancy.json" (disponible en las instrucciones de Canvas) y ubicarte en la carpeta donde lo almacenaste
import os
DIR = "/content/drive/MyDrive/2. MNA Tec/Ciencia Analitica TC5053.10/Materiales para Tareas"
os.chdir(DIR)

In [27]:
# consultancy.json almacena la clave privada para autenticar una cuenta y autorizar el acceso a los servicios
# A través de la función Certificate(), se regresa una credencial inicializada, que puedes utilizar para crear una nueva instancia de la aplicación
cred = credentials.Certificate('consultancy.json')
firebase_admin.initialize_app(cred)
db = firestore.client()

10.	Investiga cómo leer la colección `EMPLOYEE` y mostrar su contenido en un dataframe. Asegúrate de incluir el `id` en el resultado

In [28]:
employees_ref = db.collection('EMPLOYEE')

In [29]:
employees = employees_ref.stream()

In [30]:
employee_data = []

In [31]:
for doc in db.collection('EMPLOYEE').stream():
    data = doc.to_dict()
    data['id'] = doc.id
    employee_data.append(data)

In [32]:
employee_df = pd.DataFrame(employee_data)

In [33]:
employee_df = employee_df[
    ['id', 'emp_fname', 'emp_lname', 'emp_hiredate']
]

In [34]:
employee_df

                     id emp_fname   emp_lname              emp_hiredate
0  8LcLuxVHGAd2d9IQc5jF     David      Senior 1989-07-12 06:00:00+00:00
1  Fzd60D6Z2CU4n0wVV8YN   William  Smithfield 2004-06-04 05:00:00+00:00
2  lX5xuQ5w3i6ib2ExccWY      John        News 2000-11-08 06:00:00+00:00
3  yocFj2lichOkbAj9NBfp      June     Arbough 1996-12-01 06:00:00+00:00

In [35]:
firebase_admin.delete_app(firebase_admin.get_app())

---

**Declaración de uso de IA**

*   OpenAI. (2026). *ChatGPT (basado en GPT-4)* [Modelo de lenguaje grande], utilizado para revisión de código y generación de sugerencias para resolución de warnings. https://chat.openai.com/

---